---
title: "Get started with funbiogeo"
output: rmarkdown::html_vignette
vignette: >
  %\VignetteIndexEntry{Get started with funbiogeo}
  %\VignetteEncoding{UTF-8}
  %\VignetteEngine{knitr::rmarkdown}
editor_options: 
  chunk_output_type: inline
---

```{r, include = FALSE}
knitr::opts_chunk$set(
  collapse = TRUE,
  comment = "#>",
  fig.width = 7,
  fig.height = 7,
  out.width = "100%",
  dpi = 100,
  pngquant = "--speed=1 --quality=50"
)
```

The aim of the `funbiogeo` package is to help users streamline the workflows in 
functional biogeography. It helps filter sites, species, 
and traits based on their trait coverage. It also provides default diagnostic 
plots and standard tables summarizing input data.

`funbiogeo` provides five vignettes to explain its functioning:

* An [introduction to `funbiogeo`](https://frbcesab.github.io/funbiogeo/articles/introduction.html)
  that describes its core features and guide you through a typical analysis.
* A vignette on [all diagnostic plots](https://frbcesab.github.io/funbiogeo/articles/diagnostic-plots.html)
  provided in the package, which details how to use each plotting function and
  how to interpret their output.
* A vignette on the [data format](https://frbcesab.github.io/funbiogeo/articles/long-format.html)
  that `funbiogeo` needs, which shows you the use of specific functions to format your data to work well within `funbiogeo`.
* A vignette on [data upscaling](https://frbcesab.github.io/funbiogeo/articles/upscaling.html)
  which explains how to leverage `funbiogeo` to aggregate automatically your data to coarser grain and
  use them in further analyses.
* A vignette focusing on [special cases](https://frbcesab.github.io/funbiogeo/articles/special-cases.html), 
  e.g. how to work with categorical traits, or how to consider intraspefic trait variations.
