---
title: "Upscaling Your Data with funbiogeo"
output: rmarkdown::html_vignette
vignette: >
  %\VignetteIndexEntry{Upscaling Your Data with funbiogeo}
  %\VignetteEngine{knitr::rmarkdown}
  %\VignetteEncoding{UTF-8}
---

```{r, include = FALSE}
knitr::opts_chunk$set(
  collapse = TRUE,
  comment = "#>"
)
```

```{r setup}
library(funbiogeo)
```

The aims of this vignette is to provide explanation on upscaling.

```{r upscale-richness, eval=FALSE}
## Upscale to grid ----
ras_richness <- fb_aggregate_site_data(site_locations = site_locations, 
                                       site_data      = rich_env, 
                                       agg_grid       = tavg)

ras_richness
```

```{r map-richness, dev=png, eval = FALSE}
fb_map_raster(ras_richness[[1]])
```

```{r map-richness-custom, dev=png, eval = FALSE}
fb_map_raster(ras_richness[[1]]) + 
  scale_fill_distiller("Number of species", palette = "Spectral") +
  theme(legend.position = "bottom") + 
  ggtitle("Trees species richness in Pennsylvania")
```

